spring:
  application:
    name: bookvault

  datasource:
    url: jdbc:postgresql://localhost:5432/bookstore
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
